name = "dynotic-uploader"
type = "javascript"

# Akun Cloudflare
account_id = "e385cd0f482f6239a6d4f2182db0aff875412" # ganti dengan account ID-mu
workers_dev = true
route = "" # kosong dulu kalo mau pakai workers.dev subdomain
compatibility_date = "2026-02-27"

# R2 binding
[[r2_buckets]]
binding = "dynotic-storage"  # nama binding di Worker
bucket_name = "dynotic-storage" # nama bucket R2-mu
preview_bucket_name = "dynotic-storage"
