name = "dynotic-uploader"
type = "javascript"

account_id = "e385cd0f482f6239a6d4f2182db0aff875412" 
workers_dev = true
route = "" 
compatibility_date = "2026-02-27"
main = "worker.js"

[[r2_buckets]]
binding = "dynotic-storage"  
bucket_name = "dynotic-storage"
preview_bucket_name = "dynotic-storage"
